/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete_principal;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Rectangle;
import java.awt.Dimension;

/**
 *
 * @author 21414215
 */
public class Vis_Registro extends JFrame implements Int_Registro {
	private JFrame frame;
	private JTextField TxF_Nombre;
	private JTextField TxF_Usuario;
	private JTextField TxF_Correo;
	private JTextField TxF_Pass;
	private JTextField TxF_RepPass;
	private JButton btnRegistrarse;
	private JButton btnCancelar;
	private Modelo modelo;
	private Controlador controlador;
	private JButton btnSalir;
	private JLabel lblRepetirPassword;
	private JLabel lblPassword;
	private JLabel lblNombre;
	private JLabel lblUsuario;
	private JLabel lblCorreo;
	private JLabel lblErrores;

	/**
	 * Creates new form Vis_Registro
	 */
	public Vis_Registro() {
		setSize(new Dimension(500, 500));
		setTitle("Registro");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lblNombre = new JLabel("Nombre");

		lblUsuario = new JLabel("Usuario");

		lblCorreo = new JLabel("Correo");

		lblPassword = new JLabel("Password");

		TxF_Nombre = new JTextField();
		TxF_Nombre.setColumns(10);

		TxF_Usuario = new JTextField();
		TxF_Usuario.setColumns(10);

		TxF_Correo = new JTextField();
		TxF_Correo.setColumns(10);

		TxF_Pass = new JTextField();
		TxF_Pass.setColumns(10);

		TxF_RepPass = new JTextField();
		TxF_RepPass.setColumns(10);

		lblRepetirPassword = new JLabel("Repetir Password");

		/**
		 * 
		 * En la ventana de Registro, al clicar en Registrarse se llama al
		 * metodo "Registro_A_Bienvenido" del Controlador y se pasa a ventana
		 * Bienvenida
		 */
		btnRegistrarse = new JButton("Registrarse");
		btnRegistrarse.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (controlador.registrar_nuevo_usuario()) {
					controlador.Registro_A_Bienvenido();
				}
			}
		});

		btnCancelar = new JButton("Cancelar");
		btnCancelar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				controlador.cancelar_Registro();

			}
		});

		btnSalir = new JButton("Salir");
		btnSalir.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				controlador.Cerrar();
			}
		});

		lblErrores = new JLabel("  ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout
				.createParallelGroup(Alignment.TRAILING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		btnRegistrarse))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(42)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.LEADING)
																				.addComponent(
																						lblRepetirPassword,
																						GroupLayout.DEFAULT_SIZE,
																						94,
																						Short.MAX_VALUE)
																				.addComponent(
																						lblPassword,
																						GroupLayout.DEFAULT_SIZE,
																						94,
																						Short.MAX_VALUE)
																				.addComponent(
																						lblNombre,
																						GroupLayout.PREFERRED_SIZE,
																						48,
																						GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createParallelGroup(
																								Alignment.TRAILING)
																								.addComponent(
																										lblUsuario,
																										GroupLayout.PREFERRED_SIZE,
																										45,
																										GroupLayout.PREFERRED_SIZE)
																								.addComponent(
																										lblCorreo,
																										GroupLayout.PREFERRED_SIZE,
																										44,
																										GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										lblErrores)
																								.addPreferredGap(
																										ComponentPlacement.RELATED)))))
								.addGroup(
										layout.createParallelGroup(
												Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(19)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.TRAILING)
																				.addComponent(
																						TxF_Pass,
																						GroupLayout.PREFERRED_SIZE,
																						146,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						TxF_RepPass,
																						GroupLayout.PREFERRED_SIZE,
																						146,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						TxF_Correo,
																						GroupLayout.PREFERRED_SIZE,
																						146,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						TxF_Usuario,
																						GroupLayout.PREFERRED_SIZE,
																						146,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						TxF_Nombre,
																						GroupLayout.PREFERRED_SIZE,
																						146,
																						GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(18)
																.addComponent(
																		btnCancelar)
																.addGap(18)
																.addComponent(
																		btnSalir)))
								.addGap(55)));
		layout.setVerticalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(32)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(
														TxF_Nombre,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(lblNombre))
								.addGap(18)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(
														TxF_Usuario,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(lblUsuario))
								.addGap(18)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(
														TxF_Correo,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(lblCorreo))
								.addGap(18)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(lblPassword)
												.addComponent(
														TxF_Pass,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addGap(18)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(
														TxF_RepPass,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(
														lblRepetirPassword))
								.addGap(15)
								.addComponent(lblErrores)
								.addGap(18)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(btnRegistrarse)
												.addComponent(btnCancelar)
												.addComponent(btnSalir))
								.addContainerGap(56, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @return the txF_Nombre
	 */
	public String getTxF_Nombre() {
		String nombre = this.TxF_Nombre.getText().toString();
		return nombre;
	}

	/**
	 * @return the txF_Usuario
	 */
	public String getTxF_Usuario() {
		String usuario = this.TxF_Usuario.getText().toString();
		return usuario;
	}

	/**
	 * @return the txF_Correo
	 */
	public String getTxF_Correo() {
		String correo = this.TxF_Correo.getText().toString();
		return correo;
	}

	/**
	 * @return the txF_Pass
	 */
	public String getTxF_Pass() {
		String password = TxF_Pass.getText().toString();
		return password;
	}

	/**
	 * @return the txF_RepPass
	 */
	public String getTxF_RepPass() {
		return TxF_RepPass.getText().toString();
	}

	/**
	 * @param modelo
	 *            the modelo to set
	 */
	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	/**
	 * @param controlador
	 *            the controlador to set
	 */
	public void setControlador(Controlador controlador) {
		this.controlador = controlador;
	}

	public void setLblErrores(String mensaje) {
		this.lblErrores.setText(mensaje);
	}

}
