/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete_principal;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Rectangle;
import java.awt.Dimension;
import java.awt.GridLayout;

/**
 *
 * @author 21414215
 */
public class Vis_Registro extends JFrame implements Int_Registro {
	private JFrame frame;
	private JTextField TxF_Nombre;
	private JTextField TxF_Usuario;
	private JTextField TxF_Correo;
	private JTextField TxF_Pass;
	private JTextField TxF_RepPass;
	private JButton btnRegistrarse;
	private JButton btnCancelar;
	private Modelo modelo;
	private Controlador controlador;
	private JButton btnSalir;
	private JLabel lblRepetirPassword;
	private JLabel lblPassword;
	private JLabel lblNombre;
	private JLabel lblUsuario;
	private JLabel lblCorreo;
	private JLabel lblErroresNombre;
	private JLabel lblErroresUsuario;
	private JLabel lblErroresCorreo;
	private JLabel lblErroresPassword;

	/**
	 * Creates new form Vis_Registro
	 */
	public Vis_Registro() {
		setSize(new Dimension(500, 500));
		setTitle("Registro");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lblNombre = new JLabel("Nombre");

		TxF_Nombre = new JTextField();
		TxF_Nombre.setColumns(10);

		/**
		 * 
		 * En la ventana de Registro, al clicar en Registrarse se llama al
		 * metodo "Registro_A_Bienvenido" del Controlador y se pasa a ventana
		 * Bienvenida
		 */

		btnCancelar = new JButton("Cancelar");
		btnCancelar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				controlador.cancelar_Registro();

			}
		});

		btnSalir = new JButton("Salir");
		btnSalir.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				controlador.Cerrar();
			}
		});
		
		lblErroresNombre = new JLabel(" ");
		
		lblErroresCorreo = new JLabel(" ");
								
										lblUsuario = new JLabel("Usuario");
						
								TxF_Usuario = new JTextField();
								TxF_Usuario.setColumns(10);
						
						lblErroresUsuario = new JLabel(" ");
				
						lblCorreo = new JLabel("Correo");
		
				TxF_Correo = new JTextField();
				TxF_Correo.setColumns(10);
		btnRegistrarse = new JButton("Registrarse");
		btnRegistrarse.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (controlador.registrar_nuevo_usuario()) {
					controlador.Registro_A_Bienvenido();
				}
			}
		});
								
										lblPassword = new JLabel("Password");
						
								TxF_Pass = new JTextField();
								TxF_Pass.setColumns(10);
						
						lblErroresPassword = new JLabel(" ");
				
						lblRepetirPassword = new JLabel("Repetir Password");
		
				TxF_RepPass = new JTextField();
				TxF_RepPass.setColumns(10);
		GroupLayout groupLayout = new GroupLayout(getContentPane());
		groupLayout.setHorizontalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addComponent(lblNombre, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addComponent(TxF_Nombre, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblErroresNombre, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
					.addContainerGap())
				.addGroup(groupLayout.createSequentialGroup()
					.addComponent(lblUsuario, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addComponent(TxF_Usuario, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblErroresUsuario, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
					.addContainerGap())
				.addGroup(groupLayout.createSequentialGroup()
					.addComponent(lblCorreo, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addComponent(TxF_Correo, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblErroresCorreo, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
					.addContainerGap())
				.addGroup(groupLayout.createSequentialGroup()
					.addComponent(lblPassword, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addComponent(TxF_Pass, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblErroresPassword, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
					.addContainerGap())
				.addGroup(groupLayout.createSequentialGroup()
					.addComponent(lblRepetirPassword, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addComponent(TxF_RepPass, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addGap(174))
				.addGroup(groupLayout.createSequentialGroup()
					.addComponent(btnRegistrarse)
					.addComponent(btnCancelar, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addComponent(btnSalir, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
					.addGap(87))
		);
		groupLayout.setVerticalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(lblNombre, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
						.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
							.addComponent(TxF_Nombre, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
							.addComponent(lblErroresNombre, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)))
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(lblUsuario, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
						.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
							.addComponent(TxF_Usuario, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
							.addComponent(lblErroresUsuario, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)))
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(lblCorreo, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
						.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
							.addComponent(TxF_Correo, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
							.addComponent(lblErroresCorreo, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)))
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(lblPassword, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
						.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
							.addComponent(TxF_Pass, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
							.addComponent(lblErroresPassword, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)))
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(lblRepetirPassword, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
						.addComponent(TxF_RepPass, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(btnRegistrarse)
						.addComponent(btnCancelar)
						.addComponent(btnSalir)))
		);
		getContentPane().setLayout(groupLayout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @return the txF_Nombre
	 */
	public String getTxF_Nombre() {
		String nombre = this.TxF_Nombre.getText().toString();
		return nombre;
	}

	/**
	 * @return the txF_Usuario
	 */
	public String getTxF_Usuario() {
		String usuario = this.TxF_Usuario.getText().toString();
		return usuario;
	}

	/**
	 * @return the txF_Correo
	 */
	public String getTxF_Correo() {
		String correo = this.TxF_Correo.getText().toString();
		return correo;
	}

	/**
	 * @return the txF_Pass
	 */
	public String getTxF_Pass() {
		String password = TxF_Pass.getText().toString();
		return password;
	}

	/**
	 * @return the txF_RepPass
	 */
	public String getTxF_RepPass() {
		return TxF_RepPass.getText().toString();
	}

	/**
	 * @param modelo
	 *            the modelo to set
	 */
	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	/**
	 * @param controlador
	 *            the controlador to set
	 */
	public void setControlador(Controlador controlador) {
		this.controlador = controlador;
	}

	/**
	 * @param lblErroresNombre the lblErroresNombre to set
	 */
	public void setLblErroresNombre(String lblErroresNombre) {
		this.lblErroresNombre.setText(lblErroresNombre);
	}

	/**
	 * @param lblErroresUsuario the lblErroresUsuario to set
	 */
	public void setLblErroresUsuario(String lblErroresUsuario) {
		this.lblErroresUsuario.setText(lblErroresUsuario);
	}

	/**
	 * @param lblErroresCorreo the lblErroresCorreo to set
	 */
	public void setLblErroresCorreo(String lblErroresCorreo) {
		this.lblErroresCorreo.setText(lblErroresCorreo);
	}

	/**
	 * @param lblErroresPassword the lblErroresPassword to set
	 */
	public void setLblErroresPassword(String lblErroresPassword) {
		this.lblErroresPassword.setText(lblErroresPassword); 
	}

	
}
